package auth

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/RK-Consulting/skill-sifter/models"
	"github.com/golang-jwt/jwt/v5"
)

// TestGenerateTokenAndParse verifies a token generated by GenerateToken can be
// parsed back with the exact same claims. This is the core guarantee the
// entire auth system depends on — if this breaks, nobody can log in.
func TestGenerateTokenAndParse(t *testing.T) {
	user := models.User{
		ID:          42,
		Email:       "test@example.com",
		Role:        "recruiter",
		CompanyName: "Acme Corp",
	}

	tokenString, err := GenerateToken(user, user.Role)
	if err != nil {
		t.Fatalf("GenerateToken returned an error: %v", err)
	}

	claims := &Claims{}
	token, err := jwt.ParseWithClaims(tokenString, claims, func(token *jwt.Token) (interface{}, error) {
		return JwtKey, nil
	})
	if err != nil {
		t.Fatalf("failed to parse generated token: %v", err)
	}
	if !token.Valid {
		t.Fatal("generated token was parsed but reported invalid")
	}

	if claims.UserID != user.ID {
		t.Errorf("UserID = %d, want %d", claims.UserID, user.ID)
	}
	if claims.Email != user.Email {
		t.Errorf("Email = %q, want %q", claims.Email, user.Email)
	}
	if claims.Role != user.Role {
		t.Errorf("Role = %q, want %q", claims.Role, user.Role)
	}
	if claims.CompanyName != user.CompanyName {
		t.Errorf("CompanyName = %q, want %q", claims.CompanyName, user.CompanyName)
	}
}

// TestGenerateTokenExpiry verifies tokens are issued with a real, near-future
// expiry — catches a regression where expiry silently stops being set.
func TestGenerateTokenExpiry(t *testing.T) {
	user := models.User{ID: 1, Email: "a@b.com", Role: "admin", CompanyName: "X"}
	tokenString, err := GenerateToken(user, user.Role)
	if err != nil {
		t.Fatalf("GenerateToken returned an error: %v", err)
	}

	claims := &Claims{}
	_, err = jwt.ParseWithClaims(tokenString, claims, func(token *jwt.Token) (interface{}, error) {
		return JwtKey, nil
	})
	if err != nil {
		t.Fatalf("failed to parse token: %v", err)
	}

	if claims.ExpiresAt == nil {
		t.Fatal("token has no expiry set")
	}
	untilExpiry := time.Until(claims.ExpiresAt.Time)
	if untilExpiry <= 0 || untilExpiry > 25*time.Hour {
		t.Errorf("token expiry is %v from now, expected roughly 24h", untilExpiry)
	}
}

// TestRoleMiddlewareAllowsPermittedRole verifies a request with an allowed
// role reaches the wrapped handler.
func TestRoleMiddlewareAllowsPermittedRole(t *testing.T) {
	called := false
	handler := RoleMiddleware("admin", "manager")(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		called = true
		w.WriteHeader(http.StatusOK)
	}))

	req := httptest.NewRequest("GET", "/", nil)
	ctx := context.WithValue(req.Context(), "role", "manager")
	req = req.WithContext(ctx)
	rec := httptest.NewRecorder()

	handler.ServeHTTP(rec, req)

	if !called {
		t.Error("handler was not called for an allowed role")
	}
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", rec.Code, http.StatusOK)
	}
}

// TestRoleMiddlewareBlocksDisallowedRole verifies a request with a role NOT
// in the allow-list is rejected with 403 and never reaches the handler.
// This is exactly the class of check that, if silently broken, would let
// any authenticated user hit admin/manager-only routes.
func TestRoleMiddlewareBlocksDisallowedRole(t *testing.T) {
	called := false
	handler := RoleMiddleware("admin", "manager")(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		called = true
		w.WriteHeader(http.StatusOK)
	}))

	req := httptest.NewRequest("GET", "/", nil)
	ctx := context.WithValue(req.Context(), "role", "recruiter")
	req = req.WithContext(ctx)
	rec := httptest.NewRecorder()

	handler.ServeHTTP(rec, req)

	if called {
		t.Error("handler was called despite role not being in the allow-list")
	}
	if rec.Code != http.StatusForbidden {
		t.Errorf("status = %d, want %d", rec.Code, http.StatusForbidden)
	}
}

// TestJwtKeyIsNotTheKnownInsecureDefault guards specifically against the
// regression just found in this codebase: JwtKey silently reverting to a
// hardcoded, publicly-known value. This test will fail loudly if that ever
// happens again, in CI, before it reaches production.
func TestJwtKeyIsNotTheKnownInsecureDefault(t *testing.T) {
	knownBadKeys := []string{
		"skill_sifter_secret_key",
	}
	for _, bad := range knownBadKeys {
		if string(JwtKey) == bad {
			t.Errorf("JwtKey is set to a known hardcoded insecure value (%q) — "+
				"JWT_SECRET env var is not being read correctly", bad)
		}
	}
}