import React,{useEffect,useState} from 'react';
import Navbar from '@/components/layout/Navbar';
import Container from '@/components/layout/Container';
import Footer from '@/components/layout/Footer';
import Button from '@/components/ui-custom/Button';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui-custom/Card';
import {resumeAIService,ResumeRecord,ResumeResult,UploadResult} from '@/services/resumeAIService';
import {toast} from 'sonner';

const ResumeAI=()=>{
 const [files,setFiles]=useState<File[]>([]);const [uploading,setUploading]=useState(false);const [rows,setRows]=useState<ResumeRecord[]>([]);const [results,setResults]=useState<ResumeResult[]>([]);const [q,setQ]=useState('');const [searching,setSearching]=useState(false);const [ollama,setOllama]=useState<any>(null);
 const load=async()=>{try{const r=await resumeAIService.list();setRows(r.data?.data||[])}catch(e){console.error(e)}};
 useEffect(()=>{load();resumeAIService.health().then(r=>setOllama(r.data?.data)).catch(()=>setOllama({available:false}))},[]);
 const upload=async()=>{if(!files.length)return;setUploading(true);try{const r=await resumeAIService.upload(files);const data=(r.data?.data||[]) as UploadResult[];setResults(data);await load();toast.success(`Processed ${data.length} resume(s)`)}catch(e:any){toast.error(e?.response?.data?.message||'Resume processing failed')}finally{setUploading(false)}};
 const search=async()=>{if(!q.trim())return;setSearching(true);try{const r=await resumeAIService.search(q);setResults(r.data?.data||[])}catch(e:any){toast.error(e?.response?.data?.message||'Search failed')}finally{setSearching(false)}};
 return <div className="min-h-screen bg-background flex flex-col"><Navbar/><main className="pt-24 pb-10 flex-grow"><Container><div className="mb-8"><h1 className="text-3xl font-semibold">Resume AI</h1><p className="text-ats-gray-500 mt-2">Upload a folder of resumes, extract name, email, phone and skills with local Ollama, then search the complete repository.</p></div>
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6"><Card className="lg:col-span-2"><CardHeader><CardTitle>Upload resume folder</CardTitle></CardHeader><CardContent><input type="file" multiple accept=".pdf,.docx,.txt,.md" onChange={e=>setFiles(Array.from(e.target.files||[]))} className="w-full border rounded-lg p-3"/><p className="text-sm text-gray-500 mt-2">Select multiple files or a folder from your browser. PDF, DOCX and text files are supported. Maximum 10MB per file.</p><div className="mt-4 flex items-center gap-3"><Button onClick={upload} disabled={!files.length||uploading}>{uploading?'Processing with Ollama…':`Process ${files.length||0} resume(s)`}</Button><span className="text-sm text-gray-500">{files.length?`${files.length} selected`:''}</span></div></CardContent></Card><Card><CardHeader><CardTitle>Local AI status</CardTitle></CardHeader><CardContent><div className={`text-lg font-semibold ${ollama?.available?'text-green-600':'text-red-600'}`}>{ollama?.available?'Ollama connected':'Ollama unavailable'}</div><div className="text-sm text-gray-500 mt-2">URL: {ollama?.url||'http://127.0.0.1:11434'}</div><div className="text-sm text-gray-500">Model: {ollama?.model||'llama3.1:8b'}</div></CardContent></Card></div>
 <Card className="mb-6"><CardHeader><CardTitle>AI resume search</CardTitle></CardHeader><CardContent><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="e.g. Java Spring AWS" className="flex-1 border rounded-lg px-3 py-2"/><Button onClick={search} disabled={searching}>{searching?'Searching…':'Search'}</Button></div></CardContent></Card>
 <Card><CardHeader><CardTitle>{results.length?'Search results':'Resume repository'}</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Name</th><th className="p-3">Email</th><th className="p-3">Phone</th><th className="p-3">Skills</th><th className="p-3">Resume</th><th className="p-3">Status</th></tr></thead><tbody>{(results.length?results:rows).map((r:any)=><tr key={r.id} className="border-b"><td className="p-3 font-medium">{r.name||'—'}</td><td className="p-3">{r.email||'—'}</td><td className="p-3">{r.phone||'—'}</td><td className="p-3 max-w-md">{r.skills||'—'}</td><td className="p-3">{r.resumeFile||r.fileName||'—'}</td><td className="p-3"><span className="rounded-full px-2 py-1 bg-gray-100">{r.resumeStatus||r.status||'—'}</span>{r.error&&<div className="text-red-500 mt-1">{r.error}</div>}</td></tr>)}{!(results.length?results:rows).length&&<tr><td colSpan={6} className="p-8 text-center text-gray-500">No resumes yet. Upload a folder to begin.</td></tr>}</tbody></table></div></CardContent></Card>
 </Container></main><Footer/></div>
};export default ResumeAI;
